name: py38stats
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - ipython
  - ipywidgets
  - jupyter
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - pandas
  - pytables
  - python=3.8.*
  - requests
  - scikit-learn
  - scipy
  - seaborn
